# Name your workflow
name: CI

# Set on which events you want run the actions.
# In this  case the workflow will run on push for master and on pull request for master and development branches
on:
  push:
    branches: [development]
  pull_request:
    branches: [master]
jobs:
  # This workflow contains a job called "integration"
  integration:
    # A strategy that defines different variations of an environment to run each job in.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16.13.1]
    # The runners that the job will run on
    runs-on: ${{ matrix.os }}
