# Name your workflow
name: CI

# Set on which events you want run the actions.
# In this  case the workflow will run on push for master and on pull request for master and development branches
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, development]
